// lib.mjs — pure functions shared by generate.mjs and validate.mjs (no file I/O here).
import { dirname as _dirname, resolve as _resolve } from "node:path";

export const PARTS = [
  { id: "0", title: "Part 0 · Before you start", dir: "part-0-start" },
  { id: "A1", title: "Part A1 · PostgreSQL & SQL", dir: "a1-postgres" },
  { id: "A2", title: "Part A2 · Axum", dir: "a2-axum" },
  { id: "A3", title: "Part A3 · SeaORM", dir: "a3-seaorm" },
  { id: "A4", title: "Part A4 · Putting it together", dir: "a4-together" },
  { id: "B", title: "Part B · Capstone: ShopRS", dir: "b-capstone" },
];
const partOf = (t) => PARTS.find((p) => p.id === t.part);

export const HEADINGS = {
  lesson: [
    "## By the end of this lesson",
    "## What & why",
    "## The idea, slowly",
    "## You might be wondering…",
    "## Coming from another language?",
    "## Common mistakes",
    "## More examples",
    "## Your turn",
    "## Quick check",
    "## Remember this",
    "## Go deeper",
  ],
  project: [
    "## What you'll build",
    "## What you need to know",
    "## The spec",
    "## Build it, step by step",
    "## Reference solution, line by line",
    "## Stretch goals",
    "## Remember this",
  ],
  cheatsheet: [],
  checklist: [],
};

export const TIERS = ["### 🟢 Guided", "### 🟡 Tweak", "### 🔴 From scratch"];

export const pagePath = (t) => `${partOf(t).dir}/${t.slug}.md`;

const bullets = (xs) => (xs || []).map((x) => `- ${x}`).join("\n");
const authoring = (what) => `<!-- AUTHORING: ${what} -->`;

function linkTo(slug, bySlug) {
  const t = bySlug.get(slug);
  if (!t) return null;
  return t.status === "published" ? `- [${t.title}](../${pagePath(t)})` : `- ${t.title} (coming soon)`;
}

function goDeeper(t, bySlug) {
  const parts = [];
  const refs = [...(t.rfhLinks || []), ...(t.links || [])]
    .map((l) => `- [${l.label}](${l.href})${l.note ? ` — ${l.note}` : ""}`);
  if (refs.length) parts.push(refs.join("\n"));
  const next = (t.next || []).map((s) => linkTo(s, bySlug)).filter(Boolean);
  if (next.length) parts.push(`**Next:**\n\n${next.join("\n")}`);
  return parts.join("\n\n") || authoring("official docs + Rust for Humans links");
}

function lessonStub(t, bySlug) {
  const tier = (h) => `${h}\n\n${authoring("exercise")}\n\n<details><summary>Solution</summary>\n\n${authoring("solution")}\n\n</details>`;
  const body = {
    "## By the end of this lesson": bullets(t.outcomes) || authoring("2–3 concrete outcomes"),
    "## What & why": `${t.summary || ""}\n\n${authoring("real-world problem + plain-language analogy")}`,
    "## The idea, slowly": `${authoring("small steps; after each listing add ### Line by line and ### Run it")}`,
    "## You might be wondering…": authoring("pre-emptive FAQ: the questions a confused beginner asks here"),
    "## Coming from another language?": authoring("Express / Flask / Spring / Go equivalents"),
    "## Common mistakes": authoring("real errors, what they mean, the fix"),
    "## More examples": authoring("4 × (### title, one-line hook, code)"),
    "## Your turn": TIERS.map(tier).join("\n\n"),
    "## Quick check": `<div class="quiz" data-topic="${t.slug}"></div>`,
    "## Remember this": authoring("3–5 takeaways"),
    "## Go deeper": goDeeper(t, bySlug),
  };
  return HEADINGS.lesson.map((h) => `${h}\n\n${body[h]}`).join("\n\n");
}

export function stubFor(t, bySlug) {
  const head = `# ${t.title}\n\n> **${t.level}** · ${partOf(t).title}`;
  let body;
  if (t.kind === "lesson") body = lessonStub(t, bySlug);
  else if (t.kind === "project") body = HEADINGS.project.map((h) => `${h}\n\n${authoring(h.slice(3))}`).join("\n\n");
  else if (t.kind === "checklist") body = `${authoring("- [ ] items, each linking to the lesson that teaches it")}`;
  else body = `${authoring("one-page How do I…? list, each item links to its lesson")}`;
  return `${head}\n\n${body}\n`;
}

export function summaryFor(topics) {
  let s = "# Summary\n\n[Introduction](introduction.md)\n[Glossary](glossary.md)\n";
  for (const p of PARTS) {
    const inPart = topics.filter((t) => t.part === p.id);
    if (!inPart.length) continue;
    s += `\n# ${p.title}\n\n`;
    for (const t of inPart) s += t.status === "published" ? `- [${t.title}](${pagePath(t)})\n` : `- [${t.title}]()\n`;
  }
  return s + "\n---\n\n[Review & flashcards](review.md)\n";
}

const quizzable = (t) => t.status === "published" && t.kind === "lesson";

export function bundleFor(topics, banks) {
  const live = topics.filter(quizzable);
  const q = Object.fromEntries(live.filter((t) => banks[t.slug]).map((t) => [t.slug, banks[t.slug]]));
  const order = live.map((t) => ({ slug: t.slug, title: t.title, category: partOf(t).title }));
  return (
    "// AUTO-GENERATED by tools/generate.mjs — do not edit by hand.\n" +
    `window.RUST_QUESTIONS = ${JSON.stringify(q)};\n` +
    `window.RUST_TOPIC_ORDER = ${JSON.stringify(order)};\n`
  );
}

export const questionStub = (t) =>
  JSON.stringify({ topic: t.slug, title: t.title, quiz: [], flashcards: [] }, null, 2) + "\n";

export { quizzable };

// ---------------------------------------------------------------------------
// Validation

const FENCE = /^ {0,3}(```|~~~)/;

export function stripFences(md) {
  let inFence = false;
  return md.split("\n").map((line) => {
    if (FENCE.test(line)) { inFence = !inFence; return ""; }
    return inFence ? "" : line;
  }).join("\n");
}

export function headingId(text) {
  let id = "";
  for (const ch of text) {
    if (/[\p{L}\p{N}_-]/u.test(ch)) id += ch.toLowerCase();
    else if (/\s/.test(ch)) id += "-";
  }
  return id;
}

export function glossaryIds(md) {
  const ids = new Set();
  for (const m of stripFences(md).matchAll(/^#{2,4} +(.+)$/gm)) ids.add(headingId(m[1].trim()));
  return ids;
}

const BANNED = ["simply", "just", "obviously", "trivially"];

function sectionBody(prose, heading) {
  const start = prose.indexOf(`\n${heading}\n`);
  if (start < 0) return "";
  const rest = prose.slice(start + heading.length + 2);
  const end = rest.search(/^## /m);
  return end < 0 ? rest : rest.slice(0, end);
}

export function checkPage({ topic: t, md, mdFile, root, glossary, exists, read }) {
  const errors = [], warnings = [];
  const prose = stripFences(md);
  const required = HEADINGS[t.kind] || [];

  // 1. required headings: present, and in order
  const found = [...prose.matchAll(/^## .+$/gm)].map((m) => m[0].trim());
  for (const h of required) if (!found.includes(h)) errors.push(`missing section "${h}"`);
  const seq = found.filter((h) => required.includes(h));
  if (required.every((h) => found.includes(h)) && seq.join("|") !== required.join("|"))
    errors.push(`sections out of order: expected ${required.join(" → ")}`);

  // 2. lesson-only rules
  if (t.kind === "lesson") {
    if (!md.includes(`<div class="quiz" data-topic="${t.slug}"></div>`)) errors.push("quiz mount div missing or wrong slug");
    const turn = sectionBody(prose, "## Your turn");
    let at = -1;
    for (const tier of TIERS) {
      const i = turn.indexOf(tier);
      if (i <= at) errors.push(`"## Your turn" is missing "${tier}" (or it is out of order)`);
      else at = i;
    }
    if (md.split("\n").some((l) => FENCE.test(l)) && !/^### Line by line$/m.test(prose))
      errors.push('page has code but no "### Line by line" section');
  }

  // 3. checklist items must link to a lesson
  if (t.kind === "checklist")
    for (const line of prose.split("\n"))
      if (/^- \[ \]/.test(line) && !line.includes("]("))
        errors.push(`checklist item has no lesson link: ${line.slice(6).trim()}`);
  if (t.kind === "cheatsheet" && !prose.includes("](")) warnings.push("cheat sheet links to no lessons");

  // 4. includes resolve (scan raw md: includes live inside fences)
  for (const m of md.matchAll(/\{\{#include\s+([^}\s]+)\s*\}\}/g)) {
    const [rel, ...rest] = m[1].split(":");
    const file = _resolve(_dirname(mdFile), rel);
    if (!exists(file)) { errors.push(`include file not found: ${rel}`); continue; }
    if (!rest.length) continue;
    if (/^\d/.test(rest[0])) { warnings.push(`include ${m[1]} uses line numbers — use an ANCHOR so edits can't shift it`); continue; }
    const name = rest[0];
    const src = read(file);
    const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    if (!new RegExp(`ANCHOR:\\s*${esc}\\b`).test(src) || !new RegExp(`ANCHOR_END:\\s*${esc}\\b`).test(src))
      errors.push(`anchor "${name}" not found (ANCHOR + ANCHOR_END) in ${rel}`);
  }

  // 5. leftovers, banned words, glossary links, codeDir
  if (md.includes("AUTHORING:")) errors.push("leftover AUTHORING placeholder");
  const plain = prose.replace(/`[^`\n]*`/g, "");
  for (const w of BANNED) {
    const n = (plain.match(new RegExp(`\\b${w}\\b`, "gi")) || []).length;
    if (n) warnings.push(`banned word "${w}" used ${n}×`);
  }
  for (const m of md.matchAll(/glossary\.md#([\w-]+)/g))
    if (!glossary.has(m[1])) warnings.push(`glossary link #${m[1]} has no matching glossary heading`);
  if (t.codeDir && !exists(_resolve(root, t.codeDir))) errors.push(`codeDir does not exist: ${t.codeDir}`);

  return { errors, warnings };
}

export function checkBank(t, bank) {
  const errors = [], warnings = [];
  const quiz = Array.isArray(bank.quiz) ? bank.quiz : [];
  const cards = Array.isArray(bank.flashcards) ? bank.flashcards : [];
  if (quiz.length < 4) warnings.push(`quiz has fewer than 4 questions (${quiz.length})`);
  if (!cards.length) warnings.push("no flashcards");
  quiz.forEach((q, i) => {
    if (!q.q) errors.push(`quiz[${i}] missing question text`);
    if (!Array.isArray(q.options) || q.options.length < 2) errors.push(`quiz[${i}] needs at least 2 options`);
    if (typeof q.answer !== "number" || q.answer < 0 || q.answer >= (q.options || []).length)
      errors.push(`quiz[${i}] answer index out of range`);
    if (!q.explain) warnings.push(`quiz[${i}] has no explanation`);
  });
  cards.forEach((c, i) => { if (!c.front || !c.back) errors.push(`flashcard[${i}] missing front/back`); });
  return { errors, warnings };
}

export function checkTopics(topics) {
  const errors = [], seen = new Set();
  for (const t of topics) {
    if (seen.has(t.slug)) errors.push(`duplicate slug ${t.slug}`);
    seen.add(t.slug);
    if (!PARTS.some((p) => p.id === t.part)) errors.push(`${t.slug}: unknown part ${t.part}`);
    if (!(t.kind in HEADINGS)) errors.push(`${t.slug}: unknown kind ${t.kind}`);
    if (t.status === "published" && t.kind === "lesson" && (!t.outcomes || t.outcomes.length < 2))
      errors.push(`${t.slug}: published lesson needs at least 2 outcomes`);
  }
  return errors;
}
