// lib.mjs — pure functions shared by generate.mjs and validate.mjs (no file I/O here).

export const PARTS = [
  { id: "0", title: "Part 0 · Before you start", dir: "part-0-start" },
  { id: "A1", title: "Part A1 · PostgreSQL & SQL", dir: "a1-postgres" },
  { id: "A2", title: "Part A2 · Axum", dir: "a2-axum" },
  { id: "A3", title: "Part A3 · SeaORM", dir: "a3-seaorm" },
  { id: "A4", title: "Part A4 · Putting it together", dir: "a4-together" },
  { id: "B", title: "Part B · Capstone: ShopRS", dir: "b-capstone" },
];
const partOf = (t) => PARTS.find((p) => p.id === t.part);

export const HEADINGS = {
  lesson: [
    "## By the end of this lesson",
    "## What & why",
    "## The idea, slowly",
    "## You might be wondering…",
    "## Coming from another language?",
    "## Common mistakes",
    "## More examples",
    "## Your turn",
    "## Quick check",
    "## Remember this",
    "## Go deeper",
  ],
  project: [
    "## What you'll build",
    "## What you need to know",
    "## The spec",
    "## Build it, step by step",
    "## Reference solution, line by line",
    "## Stretch goals",
    "## Remember this",
  ],
  cheatsheet: [],
  checklist: [],
};

export const TIERS = ["### 🟢 Guided", "### 🟡 Tweak", "### 🔴 From scratch"];

export const pagePath = (t) => `${partOf(t).dir}/${t.slug}.md`;

const bullets = (xs) => (xs || []).map((x) => `- ${x}`).join("\n");
const authoring = (what) => `<!-- AUTHORING: ${what} -->`;

function linkTo(slug, bySlug) {
  const t = bySlug.get(slug);
  if (!t) return null;
  return t.status === "published" ? `- [${t.title}](../${pagePath(t)})` : `- ${t.title} (coming soon)`;
}

function goDeeper(t, bySlug) {
  const parts = [];
  const refs = [...(t.rfhLinks || []), ...(t.links || [])]
    .map((l) => `- [${l.label}](${l.href})${l.note ? ` — ${l.note}` : ""}`);
  if (refs.length) parts.push(refs.join("\n"));
  const next = (t.next || []).map((s) => linkTo(s, bySlug)).filter(Boolean);
  if (next.length) parts.push(`**Next:**\n\n${next.join("\n")}`);
  return parts.join("\n\n") || authoring("official docs + Rust for Humans links");
}

function lessonStub(t, bySlug) {
  const tier = (h) => `${h}\n\n${authoring("exercise")}\n\n<details><summary>Solution</summary>\n\n${authoring("solution")}\n\n</details>`;
  const body = {
    "## By the end of this lesson": bullets(t.outcomes) || authoring("2–3 concrete outcomes"),
    "## What & why": `${t.summary || ""}\n\n${authoring("real-world problem + plain-language analogy")}`,
    "## The idea, slowly": `${authoring("small steps; after each listing add ### Line by line and ### Run it")}`,
    "## You might be wondering…": authoring("pre-emptive FAQ: the questions a confused beginner asks here"),
    "## Coming from another language?": authoring("Express / Flask / Spring / Go equivalents"),
    "## Common mistakes": authoring("real errors, what they mean, the fix"),
    "## More examples": authoring("4 × (### title, one-line hook, code)"),
    "## Your turn": TIERS.map(tier).join("\n\n"),
    "## Quick check": `<div class="quiz" data-topic="${t.slug}"></div>`,
    "## Remember this": authoring("3–5 takeaways"),
    "## Go deeper": goDeeper(t, bySlug),
  };
  return HEADINGS.lesson.map((h) => `${h}\n\n${body[h]}`).join("\n\n");
}

export function stubFor(t, bySlug) {
  const head = `# ${t.title}\n\n> **${t.level}** · ${partOf(t).title}`;
  let body;
  if (t.kind === "lesson") body = lessonStub(t, bySlug);
  else if (t.kind === "project") body = HEADINGS.project.map((h) => `${h}\n\n${authoring(h.slice(3))}`).join("\n\n");
  else if (t.kind === "checklist") body = `${authoring("- [ ] items, each linking to the lesson that teaches it")}`;
  else body = `${authoring("one-page How do I…? list, each item links to its lesson")}`;
  return `${head}\n\n${body}\n`;
}

export function summaryFor(topics) {
  let s = "# Summary\n\n[Introduction](introduction.md)\n[Glossary](glossary.md)\n";
  for (const p of PARTS) {
    const inPart = topics.filter((t) => t.part === p.id);
    if (!inPart.length) continue;
    s += `\n# ${p.title}\n\n`;
    for (const t of inPart) s += t.status === "published" ? `- [${t.title}](${pagePath(t)})\n` : `- [${t.title}]()\n`;
  }
  return s + "\n---\n\n[Review & flashcards](review.md)\n";
}

const quizzable = (t) => t.status === "published" && t.kind === "lesson";

export function bundleFor(topics, banks) {
  const live = topics.filter(quizzable);
  const q = Object.fromEntries(live.filter((t) => banks[t.slug]).map((t) => [t.slug, banks[t.slug]]));
  const order = live.map((t) => ({ slug: t.slug, title: t.title, category: partOf(t).title }));
  return (
    "// AUTO-GENERATED by tools/generate.mjs — do not edit by hand.\n" +
    `window.RUST_QUESTIONS = ${JSON.stringify(q)};\n` +
    `window.RUST_TOPIC_ORDER = ${JSON.stringify(order)};\n`
  );
}

export const questionStub = (t) =>
  JSON.stringify({ topic: t.slug, title: t.title, quiz: [], flashcards: [] }, null, 2) + "\n";

export { quizzable };
